### ISSUE TITLE
ArgumentException: The parameter is incorrect.

### ISSUE THREAD

**Issue by Sohail2949000** [rffrasca/PDFKeeper#13]
![error pdf keeper](https://github.com/rffrasca/PDFKeeper/assets/118283044/ca1ecce9-0cda-4fcc-a79b-bfd62be182ba)

Dear Sir,

Thank you for the PDFkeeper software I loved it.
But I am getting a error I don't know about it.

Kindly advise us how we can solve this.

thanks.

**Comment by rffrasca** [comment]
Hello,
Thank you for the kind words. I'm glad you like PDFKeeper.

Before I can look into this issue, I will need PDFKeeper.log to see where the exception occurred. If the error happened during an upload, you would need to move the PDF being uploaded out of C:\Users\<user>\AppData\Roaming\Robert F. Frasca\PDFKeeper\UploadStaging to prevent PDFKeeper from trying to upload it again.

Thanks,
Robert

**Comment by Sohail2949000** [comment]
Hello Sir,

Kindly find attached PDFKeeper.log for your reference.

Same happened before few days, I thought may be I deleted or move something while backing up sqlite db. 
I uninstalled it and install agian but after couple of files it shows again.


Thanks.
[PDFKeeper.log](https://github.com/rffrasca/PDFKeeper/files/13317171/PDFKeeper.log)

**Comment by rffrasca** [comment]
After reviewing the log, the unhandled exception is occurring while extracting text using OCR.

During the upload, the PDF is split into separate PDF's, one per page. Each page is processed as follows: If the PDF is an image, then OCR will be used, if text, then IText will be used to extract text. If IText is unable to extract text, then OCR is used. If the PDF contains both image and text and you specified to OCR pages with both text and image data, then OCR is used, otherwise, IText will be used to only extract text, the images will be ignored.

This strategy gives the most complete text extraction. Keep in mind, OCR is a "very expensive" operation that uses a lot of system resources (memory, CPU, and disk). 5-6 minutes to process a 10MB PDF containing all images and then insert into a local database is what I would expect to see,

I know you have some additional questions. The best place for that is in discussions. Feel free to start a discussion and we can continue the conversation there. I would like to focus on the reported issue here.

The exception contains the message: "Image dimensions are too large! Check MaxImageDimension for maximum allowed image dimensions". I'm thinking that one or more pages in the PDF contains an image with dimensions that are exceeding MaxImageDimension which cannot be modified as it is defined in the Windows OCR engine. This is something I have not seen before.

Is it possible to provide a sample PDF that can cause the error but does not contain any sensitive data?

**Comment by Sohail2949000** [comment]
Hello 

Sure, Kindly find the attached pdf for your reference.

Regards.
[212457-Golden Cup.pdf](https://github.com/rffrasca/PDFKeeper/files/13320728/212457-Golden.Cup.pdf)

**Comment by rffrasca** [comment]
Thank you for providing the PDF. With it, I was able to reproduce the issue. The exception is occurring when trying to OCR page 3. Do you need text extraction from pages that contain a photo like the one in the PDF you provided?

**Comment by Sohail2949000** [comment]
Yes Sir these PDFs are our invoices and pictures for proof and references.

is the issue solved? because I was waiting for your answer in order to start using PDFKeeper again.

Thanks again for your time and effort in this issue.

**Comment by rffrasca** [comment]
The issue is with the page in the PDF that contains the photo. The page size exceeds that set by the Windows OCR Engine. The best I can do is add a check to skip any page that exceeds the dimensions set by the Windows OCR Engine in the next version. I am currently focusing on version 9.0.0 which is not going to be released until end of 2023 or early 2024.

**Comment by Sohail2949000** [comment]
Noted.

We will be waiting for the new version.

Thanks
Sohail

**Comment by rffrasca** [comment]
PDFKeeper 9.0.0 was released today.
