### ISSUE TITLE
Multiple file additions

### ISSUE THREAD

**Issue by tresero** [rffrasca/PDFKeeper#28]
Is there any way to add entire directories/subdirectories?

**Comment by tresero** [comment]
Even manually adding files doesn't add any. Database opens, so that's not the issue, but no documents ever show up.

**Comment by rffrasca** [comment]
Yes, you can add directories of PDF documents. You add them using the Upload folder that gets created on the Desktop and in the Downloads folder. The help file contains two topics that cover this "Uploading PDF Documents from outside of PDFKeeper" and "Uploading PDF Documents using Upload Profile Folders".

After adding manually and no documents show up the list. Select the Documents menu and then Find. Next, select All Documents and see if that returns the documents that were added.

**Comment by tresero** [comment]
None of that works. Always zero files.

Not to mention, not responding for hours. If it's adding something, I don't know. I let it go overnight.

![image](https://github.com/rffrasca/PDFKeeper/assets/1476286/561a4b19-a10d-4aff-9b0e-20f01a952406)

**Comment by tresero** [comment]
I also opened the database and there are zero records.

**Comment by rffrasca** [comment]
How large is the PDF and is it an image or text based?

**Comment by tresero** [comment]
I've tried text and OCR'd, even the text one doesn't show, it's only 90k
Here is one that is text and small

[AI as an Instrument of Musical Innovation.pdf](https://github.com/rffrasca/PDFKeeper/files/15443878/AI.as.an.Instrument.of.Musical.Innovation.pdf)

**Comment by rffrasca** [comment]
The sample document uploaded in seconds. I tried with a brand-new database and a database from an older version with some documents already in it. The version of PDFKeeper used for the test is 9.1.4 and the OS is Win10 22H2.
![image](https://github.com/rffrasca/PDFKeeper/assets/18501130/365f6206-06b1-458e-9e7d-d9c69ff4f7eb)

Can you try uploading again? But this time, open an Explorer Window to C:\Users\Jon\AppData\Roaming\Robert F. Frasca\PDFKeeper\UploadStaging. When the upload begins, the PDF with updated XMP metadata will get staged to that folder along with an XML. After the PDF is uploaded successfully, it will be deleted. Let me know what you see.

**Comment by tresero** [comment]
That worked, but I had to actually search for a document before they showed up. More of a UI thing I guess.

Thanks, I'll try some others and see what happens. Are there any specific limits?

**Comment by rffrasca** [comment]
The UI doesn't open directly to view; however, you can have it open showing flagged documents on startup.

The reason why the UI doesn't open showing all documents is because PDFKeeper is also designed for client server using Oracle and these databases have the potential to contain 1000's of documents.

In the meantime, you can go into Find and select all documents after opening PDFKeeper, the list will refresh after every insert, update, and delete. What I can do is add a setting that will show all documents on startup if you like?

As far as limits go, SQLite does have a storage limit but, it is very large and shouldn't be a concern. Here is the link: https://www.sqlite.org/limits.html.

**Comment by tresero** [comment]
Thanks! and you can add if easy, if not, no worries.
